import Sidenav from "@/components/native/SideNav";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Ladies Sign Admin",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Sidenav />
      <div className="px-4 mt-12 lg:mt-4 lg:ml-72">{children}</div>
    </>
  );
}
