export const siteConfig = {
  BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL as string,

  // for JWT
  JWT_SECRET: process.env.NEXT_PUBLIC_JWT_SECRET as string,

  CLOUDINARY_UPLOAD_PRESET: "ladies-sign-preset",
  STEADFAST_BASE_URL: process.env.NEXT_PUBLIC_STEADFAST_BASE_URL,
  STEADFAST_API_KEY: process.env.NEXT_PUBLIC_STEADFAST_API_KEY,
  STEADFAST_SECRECT_KEY: process.env.NEXT_PUBLIC_STEADFAST_SECRECT_KEY,
}